### ISSUE TITLE
Fix Typos

### ISSUE THREAD

**Issue by raquel-oliveira** [goodlyrottenapple/muddy-children#1]
Fix names of rules that use underlines on the labels, such as $ father_Suc_n$, $Back_forw_K$, etc.

I don't know if you want to let the name exactly as it was defined in [DEAKDerivedRules](https://github.com/goodlyrottenapple/muddy-children/blob/master/docs/DEAKDerivedRules.html). If it is the case, just add `\` to print the underline. If the case is to let the whole word subscripted, you should put `{}` encircling the word. A different option is to put everything together.

**Comment by raquel-oliveira** [comment]
Maybe this is silly or maybe things like these are not actually mistyping :

<img width="706" alt="examples" src="https://user-images.githubusercontent.com/6775247/40007172-76c09322-5772-11e8-82e7-51d5a196f29e.png">

Extract from: https://github.com/goodlyrottenapple/muddy-children/blob/master/LaTeX/fact_23_E_vision_der_vision_cleaned_up.pdf and https://github.com/goodlyrottenapple/muddy-children/blob/master/LaTeX/fact_23_E_vision_der_vision.tex )

(if is one of the two things, just close the issue.)

**Comment by goodlyrottenapple** [comment]
Hi, these were indeed typos..Thanks! Most, if not all, should be fixed now.
